blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://your-project.github.io/metagenomicsOS/
    about: Check our comprehensive documentation first
  - name: 💬 Discussions
    url: https://github.com/your-username/metagenomicsOS/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: mailto:security@your-domain.com
    about: Report security vulnerabilities privately
